 <footer>
     <div class="wrap">
		<div class="footer_frame">
			<div class="footer_content">
				<br>
					<br>
					회사 | MORASS &nbsp;&nbsp;&nbsp;&nbsp;; 주소 | 경기 성남시 수정구 양지동 858 102호<br><br>
					대표 | 구자훈 &nbsp;&nbsp;&nbsp; 개인정보관리자 | 구자훈 &nbsp;&nbsp;&nbsp;
					호스팅제공 | 호스팅홈페이지 '닷홈'<br><br>
					전화번호 | 010-8948-2966 &nbsp;&nbsp;&nbsp; 이메일 | dy5488@naver.com
			</div>
		</div>
      </div>
	</footer>